app: expressjs-test-app
env: steady-wood
namespace: default
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.60.0
values:
  containerPort: 80
  gitRepository: bs1180/expressjs-test-app
  gitSha: '{{ .SHA }}'
  image:
    repository: 127.0.0.1:32447/expressjs-test-app
    tag: '{{ .SHA }}'
  replicas: 1
  resources:
    ignoreLimits: true
---
apiVersion: temporal.io/v1beta1
kind: TemporalNamespace
metadata:
  name: test
  namespace: test-app
spec:
  clusterRef:
    name: temporal
    namespace: temporal-cluster
  description: Namespace for the test app
  retentionPeriod: 168h #7 days
  allowDeletion: true
---
apiVersion: temporal.io/v1beta1
kind: TemporalClusterClient
metadata:
  name: my-worker
  namespace: test-app
spec:
  clusterRef:
    name: temporal
    namespace: temporal-cluster
